[build]
  command = "python Scripts/GDoc_Scrape.py"
  publish = "/opt/build/repo"
  functions = "lambda"

[build.environment]
  PYTHON_VERSION = "3.8"  # Specify your Python version here

[[plugins]]
  package = "@netlify/plugin-functions-core"

